version: '3.8'

services:
  nestjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - nestjs-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017" # lưu ý: ngoài là 27018, trong container vẫn là 27017 nhé
    volumes:
      - mongo-data:/data/db
    networks:
      - nestjs-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  nestjs-network:
    driver: bridge
