services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - ./:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - nestjs-network
    restart: unless-stopped
    command: npm run start:dev

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017" # lưu ý: ngoài là 27018, trong container vẫn là 27017 nhé
    volumes:
      - mongo-data:/data/db
    networks:
      - nestjs-network
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongo-data:


networks:
  nestjs-network:
    driver: bridge
